name: Generate Snake

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository content
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Generate the snake animation
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: mabounkoungou
          outputs: dist/snake.svg

      # Upload the snake SVG as an artifact
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake.svg
          path: dist/snake.svg

      # Commit and push the generated snake.svg to the repository
      - name: Commit and Push Snake
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add -A
          git commit -m "Updated Snake Animation"
          git push
