name: Generate Snake

on:
  # Runs every 6 hours
  schedule:
    - cron: "0 */6 * * *"
  # Allows manual trigger
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          # Replace 'mabounkoungou' with your GitHub username
          github_user_name: mabounkoungou
          outputs: dist/snake.svg

      # Commit the generated snake animation to the output branch
      - name: Commit and Push Snake Animation
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          mv dist/snake.svg output/github-contribution-grid-snake.svg
          git add output/github-contribution-grid-snake.svg
          git commit -m "Generated snake animation"
          git push
